name: 'Check for Vulnerabilities'

#on: [push]
on:
  push:
      branches:
        - main
        - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: occmundial/action-cve-clone@v2.0.1
        with:
          token: ${{ secrets.DEPENDABOTSLACKPERSONALACCESSTOKEN }}
          slack_webhook: ${{ secrets.DEPENDABOTSLACKWEBHOOKURL }}
          count: 10
